### PR TITLE
Remove client from ex_plasma

### PR DESCRIPTION
**Pull request by InoMurko**
ex plasma is a statless lib that provides utilities for transaction building.

* removes client
* bumps to 1.10.2 testing
* removes integration tests

### CODE REVIEW

**Comment by boolafish** [comment]
🤦‍♂️ I am always and still confused what ex_plasma is......

https://omisego.slack.com/archives/C9KNA675J/p1583996294083600?thread_ts=1583920759.021300&cid=C9KNA675J

So you're saying this is some really simple utility functions, and that is it? No communication across layers?

**Comment by InoMurko** [comment]
> 🤦‍♂️ I am always and still confused what ex_plasma is......
> 
> https://omisego.slack.com/archives/C9KNA675J/p1583996294083600?thread_ts=1583920759.021300&cid=C9KNA675J
> 
> So you're saying this is some really simple utility functions, and that is it? No communication across layers?

Yeah. Thats very much so. If we need utilities or interfaces like that, we should extract them from elixir-omg, where they're used and tested throughly. their implementation is correct (not only in the functional meaning) but structural (they use ABI event and function descriptions extracted from contract abi files).

**Comment by InoMurko** [comment]
the reason why it's confusing is because it was never really defined what it is or what it represents. my option is that it's primary use case is to be used in elixir-omg where it would replace half of current potatoes in elixir-omg, the other half is ecto. because of that, it should be as thing as possible. 
my advice... lets create a `ex-contract` repo, that has interactions with plasma framework functions implemented (stateless, still).

**Comment by achiurizo** [comment]
Thinking through this more, I'm fine making this library thinner and leveraging the abi contract work as the future means to generate the client interactions.

I will suggest that perhaps `ex_plasma` becomes the contract library (e.g the `ex-contract` repo _is_ this) and we move out the transaction format builder/validations into another repo(perhaps an `ex_plasma_util` or something).

**Pull request merged**
